//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianRouletteUnitTest.RussianRouletteServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/RussianRouletteServiceLibrary.Data")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RussianRouletteUnitTest.RussianRouletteServer.Message[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RussianRouletteUnitTest.RussianRouletteServer.Message[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/RussianRouletteServiceLibrary.Data")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RussianRouletteUnitTest.RussianRouletteServer.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageContent {
            get {
                return this.MessageContentField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageContentField, value) != true)) {
                    this.MessageContentField = value;
                    this.RaisePropertyChanged("MessageContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SenderId {
            get {
                return this.SenderIdField;
            }
            set {
                if ((this.SenderIdField.Equals(value) != true)) {
                    this.SenderIdField = value;
                    this.RaisePropertyChanged("SenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeSent {
            get {
                return this.TimeSentField;
            }
            set {
                if ((this.TimeSentField.Equals(value) != true)) {
                    this.TimeSentField = value;
                    this.RaisePropertyChanged("TimeSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RussianRouletteUnitTest.RussianRouletteServer.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RussianRouletteServer.IGame", CallbackContract=typeof(RussianRouletteUnitTest.RussianRouletteServer.IGameCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IGame {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Play", ReplyAction="http://tempuri.org/IGame/PlayResponse")]
        void Play();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Play", ReplyAction="http://tempuri.org/IGame/PlayResponse")]
        System.Threading.Tasks.Task PlayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/PlaceBullet", ReplyAction="http://tempuri.org/IGame/PlaceBulletResponse")]
        string PlaceBullet(int cylinderHole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/PlaceBullet", ReplyAction="http://tempuri.org/IGame/PlaceBulletResponse")]
        System.Threading.Tasks.Task<string> PlaceBulletAsync(int cylinderHole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/SpingCylinder", ReplyAction="http://tempuri.org/IGame/SpingCylinderResponse")]
        string SpingCylinder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/SpingCylinder", ReplyAction="http://tempuri.org/IGame/SpingCylinderResponse")]
        System.Threading.Tasks.Task<string> SpingCylinderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Shoot", ReplyAction="http://tempuri.org/IGame/ShootResponse")]
        bool Shoot(RussianRouletteUnitTest.RussianRouletteServer.User player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Shoot", ReplyAction="http://tempuri.org/IGame/ShootResponse")]
        System.Threading.Tasks.Task<bool> ShootAsync(RussianRouletteUnitTest.RussianRouletteServer.User player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/SendMessage", ReplyAction="http://tempuri.org/IGame/SendMessageResponse")]
        void SendMessage(RussianRouletteUnitTest.RussianRouletteServer.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/SendMessage", ReplyAction="http://tempuri.org/IGame/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(RussianRouletteUnitTest.RussianRouletteServer.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/DetermineWinnder", ReplyAction="http://tempuri.org/IGame/DetermineWinnderResponse")]
        string DetermineWinnder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/DetermineWinnder", ReplyAction="http://tempuri.org/IGame/DetermineWinnderResponse")]
        System.Threading.Tasks.Task<string> DetermineWinnderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Rematch", ReplyAction="http://tempuri.org/IGame/RematchResponse")]
        string Rematch();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Rematch", ReplyAction="http://tempuri.org/IGame/RematchResponse")]
        System.Threading.Tasks.Task<string> RematchAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/PlayerSentMessage")]
        void PlayerSentMessage();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameChannel : RussianRouletteUnitTest.RussianRouletteServer.IGame, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameClient : System.ServiceModel.DuplexClientBase<RussianRouletteUnitTest.RussianRouletteServer.IGame>, RussianRouletteUnitTest.RussianRouletteServer.IGame {
        
        public GameClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Play() {
            base.Channel.Play();
        }
        
        public System.Threading.Tasks.Task PlayAsync() {
            return base.Channel.PlayAsync();
        }
        
        public string PlaceBullet(int cylinderHole) {
            return base.Channel.PlaceBullet(cylinderHole);
        }
        
        public System.Threading.Tasks.Task<string> PlaceBulletAsync(int cylinderHole) {
            return base.Channel.PlaceBulletAsync(cylinderHole);
        }
        
        public string SpingCylinder() {
            return base.Channel.SpingCylinder();
        }
        
        public System.Threading.Tasks.Task<string> SpingCylinderAsync() {
            return base.Channel.SpingCylinderAsync();
        }
        
        public bool Shoot(RussianRouletteUnitTest.RussianRouletteServer.User player) {
            return base.Channel.Shoot(player);
        }
        
        public System.Threading.Tasks.Task<bool> ShootAsync(RussianRouletteUnitTest.RussianRouletteServer.User player) {
            return base.Channel.ShootAsync(player);
        }
        
        public void SendMessage(RussianRouletteUnitTest.RussianRouletteServer.Message message) {
            base.Channel.SendMessage(message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(RussianRouletteUnitTest.RussianRouletteServer.Message message) {
            return base.Channel.SendMessageAsync(message);
        }
        
        public string DetermineWinnder() {
            return base.Channel.DetermineWinnder();
        }
        
        public System.Threading.Tasks.Task<string> DetermineWinnderAsync() {
            return base.Channel.DetermineWinnderAsync();
        }
        
        public string Rematch() {
            return base.Channel.Rematch();
        }
        
        public System.Threading.Tasks.Task<string> RematchAsync() {
            return base.Channel.RematchAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RussianRouletteServer.IPortal")]
    public interface IPortal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/RegisterUser", ReplyAction="http://tempuri.org/IPortal/RegisterUserResponse")]
        string RegisterUser(RussianRouletteUnitTest.RussianRouletteServer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/RegisterUser", ReplyAction="http://tempuri.org/IPortal/RegisterUserResponse")]
        System.Threading.Tasks.Task<string> RegisterUserAsync(RussianRouletteUnitTest.RussianRouletteServer.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPortalChannel : RussianRouletteUnitTest.RussianRouletteServer.IPortal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PortalClient : System.ServiceModel.ClientBase<RussianRouletteUnitTest.RussianRouletteServer.IPortal>, RussianRouletteUnitTest.RussianRouletteServer.IPortal {
        
        public PortalClient() {
        }
        
        public PortalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PortalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RegisterUser(RussianRouletteUnitTest.RussianRouletteServer.User user) {
            return base.Channel.RegisterUser(user);
        }
        
        public System.Threading.Tasks.Task<string> RegisterUserAsync(RussianRouletteUnitTest.RussianRouletteServer.User user) {
            return base.Channel.RegisterUserAsync(user);
        }
    }
}
