//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianRouletteClient.RussianRouletteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/RussianRouletteServiceLibrary.Data")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RussianRouletteClient.RussianRouletteService.Game[] GamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RussianRouletteClient.RussianRouletteService.UMessage[] UMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RussianRouletteClient.RussianRouletteService.Game[] Games {
            get {
                return this.GamesField;
            }
            set {
                if ((object.ReferenceEquals(this.GamesField, value) != true)) {
                    this.GamesField = value;
                    this.RaisePropertyChanged("Games");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RussianRouletteClient.RussianRouletteService.UMessage[] UMessages {
            get {
                return this.UMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.UMessagesField, value) != true)) {
                    this.UMessagesField = value;
                    this.RaisePropertyChanged("UMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wins {
            get {
                return this.WinsField;
            }
            set {
                if ((this.WinsField.Equals(value) != true)) {
                    this.WinsField = value;
                    this.RaisePropertyChanged("Wins");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Game", Namespace="http://schemas.datacontract.org/2004/07/RussianRouletteServiceLibrary.Data")]
    [System.SerializableAttribute()]
    public partial class Game : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FirstPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecondPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RussianRouletteClient.RussianRouletteService.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WinnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] _cylinderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RussianRouletteClient.RussianRouletteService.User[] playerListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstPlayer {
            get {
                return this.FirstPlayerField;
            }
            set {
                if ((this.FirstPlayerField.Equals(value) != true)) {
                    this.FirstPlayerField = value;
                    this.RaisePropertyChanged("FirstPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecondPlayer {
            get {
                return this.SecondPlayerField;
            }
            set {
                if ((this.SecondPlayerField.Equals(value) != true)) {
                    this.SecondPlayerField = value;
                    this.RaisePropertyChanged("SecondPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RussianRouletteClient.RussianRouletteService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Winner {
            get {
                return this.WinnerField;
            }
            set {
                if ((this.WinnerField.Equals(value) != true)) {
                    this.WinnerField = value;
                    this.RaisePropertyChanged("Winner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] _cylinder {
            get {
                return this._cylinderField;
            }
            set {
                if ((object.ReferenceEquals(this._cylinderField, value) != true)) {
                    this._cylinderField = value;
                    this.RaisePropertyChanged("_cylinder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RussianRouletteClient.RussianRouletteService.User[] playerList {
            get {
                return this.playerListField;
            }
            set {
                if ((object.ReferenceEquals(this.playerListField, value) != true)) {
                    this.playerListField = value;
                    this.RaisePropertyChanged("playerList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UMessage", Namespace="http://schemas.datacontract.org/2004/07/RussianRouletteServiceLibrary.Data")]
    [System.SerializableAttribute()]
    public partial class UMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RussianRouletteClient.RussianRouletteService.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageContent {
            get {
                return this.MessageContentField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageContentField, value) != true)) {
                    this.MessageContentField = value;
                    this.RaisePropertyChanged("MessageContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SenderId {
            get {
                return this.SenderIdField;
            }
            set {
                if ((this.SenderIdField.Equals(value) != true)) {
                    this.SenderIdField = value;
                    this.RaisePropertyChanged("SenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeSent {
            get {
                return this.TimeSentField;
            }
            set {
                if ((this.TimeSentField.Equals(value) != true)) {
                    this.TimeSentField = value;
                    this.RaisePropertyChanged("TimeSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RussianRouletteClient.RussianRouletteService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RussianRouletteService.IGame", CallbackContract=typeof(RussianRouletteClient.RussianRouletteService.IGameCallback))]
    public interface IGame {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Play", ReplyAction="http://tempuri.org/IGame/PlayResponse")]
        void Play(int gameId, RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Play", ReplyAction="http://tempuri.org/IGame/PlayResponse")]
        System.Threading.Tasks.Task PlayAsync(int gameId, RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/PlaceBullet", ReplyAction="http://tempuri.org/IGame/PlaceBulletResponse")]
        void PlaceBullet(int gameId, int cylinderHole, RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/PlaceBullet", ReplyAction="http://tempuri.org/IGame/PlaceBulletResponse")]
        System.Threading.Tasks.Task PlaceBulletAsync(int gameId, int cylinderHole, RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/SpinCylinder", ReplyAction="http://tempuri.org/IGame/SpinCylinderResponse")]
        void SpinCylinder(int gameId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/SpinCylinder", ReplyAction="http://tempuri.org/IGame/SpinCylinderResponse")]
        System.Threading.Tasks.Task SpinCylinderAsync(int gameId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Shoot", ReplyAction="http://tempuri.org/IGame/ShootResponse")]
        bool Shoot(int gameId, RussianRouletteClient.RussianRouletteService.User player, int chosenHole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Shoot", ReplyAction="http://tempuri.org/IGame/ShootResponse")]
        System.Threading.Tasks.Task<bool> ShootAsync(int gameId, RussianRouletteClient.RussianRouletteService.User player, int chosenHole);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/SendMessage")]
        void SendMessage(int gameId, RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/SendMessage")]
        System.Threading.Tasks.Task SendMessageAsync(int gameId, RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Rematch", ReplyAction="http://tempuri.org/IGame/RematchResponse")]
        void Rematch(int gameId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Rematch", ReplyAction="http://tempuri.org/IGame/RematchResponse")]
        System.Threading.Tasks.Task RematchAsync(int gameId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Leave", ReplyAction="http://tempuri.org/IGame/LeaveResponse")]
        void Leave(int gameId, RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Leave", ReplyAction="http://tempuri.org/IGame/LeaveResponse")]
        System.Threading.Tasks.Task LeaveAsync(int gameId, RussianRouletteClient.RussianRouletteService.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/PlayerSentMessage")]
        void PlayerSentMessage(RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/PlayerLeft")]
        void PlayerLeft(RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/PlayerReady")]
        void PlayerReady(RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/PlayerLost")]
        void PlayerLost(RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/BulletPlaced")]
        void BulletPlaced(RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/CylinderSpun")]
        void CylinderSpun(RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/RematchRequested")]
        void RematchRequested(RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/YourTurn")]
        void YourTurn(RussianRouletteClient.RussianRouletteService.User user, int nextHole);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/FireAlive")]
        void FireAlive(string nickName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameChannel : RussianRouletteClient.RussianRouletteService.IGame, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameClient : System.ServiceModel.DuplexClientBase<RussianRouletteClient.RussianRouletteService.IGame>, RussianRouletteClient.RussianRouletteService.IGame {
        
        public GameClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Play(int gameId, RussianRouletteClient.RussianRouletteService.User user) {
            base.Channel.Play(gameId, user);
        }
        
        public System.Threading.Tasks.Task PlayAsync(int gameId, RussianRouletteClient.RussianRouletteService.User user) {
            return base.Channel.PlayAsync(gameId, user);
        }
        
        public void PlaceBullet(int gameId, int cylinderHole, RussianRouletteClient.RussianRouletteService.User user) {
            base.Channel.PlaceBullet(gameId, cylinderHole, user);
        }
        
        public System.Threading.Tasks.Task PlaceBulletAsync(int gameId, int cylinderHole, RussianRouletteClient.RussianRouletteService.User user) {
            return base.Channel.PlaceBulletAsync(gameId, cylinderHole, user);
        }
        
        public void SpinCylinder(int gameId) {
            base.Channel.SpinCylinder(gameId);
        }
        
        public System.Threading.Tasks.Task SpinCylinderAsync(int gameId) {
            return base.Channel.SpinCylinderAsync(gameId);
        }
        
        public bool Shoot(int gameId, RussianRouletteClient.RussianRouletteService.User player, int chosenHole) {
            return base.Channel.Shoot(gameId, player, chosenHole);
        }
        
        public System.Threading.Tasks.Task<bool> ShootAsync(int gameId, RussianRouletteClient.RussianRouletteService.User player, int chosenHole) {
            return base.Channel.ShootAsync(gameId, player, chosenHole);
        }
        
        public void SendMessage(int gameId, RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message) {
            base.Channel.SendMessage(gameId, user, message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(int gameId, RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message) {
            return base.Channel.SendMessageAsync(gameId, user, message);
        }
        
        public void Rematch(int gameId) {
            base.Channel.Rematch(gameId);
        }
        
        public System.Threading.Tasks.Task RematchAsync(int gameId) {
            return base.Channel.RematchAsync(gameId);
        }
        
        public void Leave(int gameId, RussianRouletteClient.RussianRouletteService.User user) {
            base.Channel.Leave(gameId, user);
        }
        
        public System.Threading.Tasks.Task LeaveAsync(int gameId, RussianRouletteClient.RussianRouletteService.User user) {
            return base.Channel.LeaveAsync(gameId, user);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RussianRouletteService.IPortal", CallbackContract=typeof(RussianRouletteClient.RussianRouletteService.IPortalCallback))]
    public interface IPortal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/SignUp", ReplyAction="http://tempuri.org/IPortal/SignUpResponse")]
        string SignUp(RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/SignUp", ReplyAction="http://tempuri.org/IPortal/SignUpResponse")]
        System.Threading.Tasks.Task<string> SignUpAsync(RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/SignIn", ReplyAction="http://tempuri.org/IPortal/SignInResponse")]
        void SignIn(RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/SignIn", ReplyAction="http://tempuri.org/IPortal/SignInResponse")]
        System.Threading.Tasks.Task SignInAsync(RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/SendPublicMessage", ReplyAction="http://tempuri.org/IPortal/SendPublicMessageResponse")]
        void SendPublicMessage(RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/SendPublicMessage", ReplyAction="http://tempuri.org/IPortal/SendPublicMessageResponse")]
        System.Threading.Tasks.Task SendPublicMessageAsync(RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/SendPrivateMessage", ReplyAction="http://tempuri.org/IPortal/SendPrivateMessageResponse")]
        void SendPrivateMessage(RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/SendPrivateMessage", ReplyAction="http://tempuri.org/IPortal/SendPrivateMessageResponse")]
        System.Threading.Tasks.Task SendPrivateMessageAsync(RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/InviteToPlay", ReplyAction="http://tempuri.org/IPortal/InviteToPlayResponse")]
        void InviteToPlay(string Nickname, RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/InviteToPlay", ReplyAction="http://tempuri.org/IPortal/InviteToPlayResponse")]
        System.Threading.Tasks.Task InviteToPlayAsync(string Nickname, RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/AgreeToPlay", ReplyAction="http://tempuri.org/IPortal/AgreeToPlayResponse")]
        void AgreeToPlay(string Nickname, RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/AgreeToPlay", ReplyAction="http://tempuri.org/IPortal/AgreeToPlayResponse")]
        System.Threading.Tasks.Task AgreeToPlayAsync(string Nickname, RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/Disconnect", ReplyAction="http://tempuri.org/IPortal/DisconnectResponse")]
        void Disconnect(RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/Disconnect", ReplyAction="http://tempuri.org/IPortal/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync(RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/checkSignIn", ReplyAction="http://tempuri.org/IPortal/checkSignInResponse")]
        bool checkSignIn(RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/checkSignIn", ReplyAction="http://tempuri.org/IPortal/checkSignInResponse")]
        System.Threading.Tasks.Task<bool> checkSignInAsync(RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/GetUsersList", ReplyAction="http://tempuri.org/IPortal/GetUsersListResponse")]
        string[] GetUsersList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/GetUsersList", ReplyAction="http://tempuri.org/IPortal/GetUsersListResponse")]
        System.Threading.Tasks.Task<string[]> GetUsersListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/ReceiveTopPlayers", ReplyAction="http://tempuri.org/IPortal/ReceiveTopPlayersResponse")]
        string[] ReceiveTopPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortal/ReceiveTopPlayers", ReplyAction="http://tempuri.org/IPortal/ReceiveTopPlayersResponse")]
        System.Threading.Tasks.Task<string[]> ReceiveTopPlayersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPortalCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPortal/OnUserSignIn")]
        void OnUserSignIn(string[] userList, RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPortal/SignInSuccess")]
        void SignInSuccess(RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPortal/OnUserSignOut")]
        void OnUserSignOut(RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPortal/OnPublicMessageSent")]
        void OnPublicMessageSent(RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPortal/OnPrivateMessageSent")]
        void OnPrivateMessageSent(RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPortal/InvitedToPlay")]
        void InvitedToPlay(RussianRouletteClient.RussianRouletteService.User user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPortal/AgreedToPlay")]
        void AgreedToPlay(int gameId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPortal/UserDisconnected")]
        void UserDisconnected(string[] userList, RussianRouletteClient.RussianRouletteService.UMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPortal/GetUserList")]
        void GetUserList(RussianRouletteClient.RussianRouletteService.User[] users);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPortalChannel : RussianRouletteClient.RussianRouletteService.IPortal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PortalClient : System.ServiceModel.DuplexClientBase<RussianRouletteClient.RussianRouletteService.IPortal>, RussianRouletteClient.RussianRouletteService.IPortal {
        
        public PortalClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public PortalClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public PortalClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PortalClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PortalClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string SignUp(RussianRouletteClient.RussianRouletteService.User user) {
            return base.Channel.SignUp(user);
        }
        
        public System.Threading.Tasks.Task<string> SignUpAsync(RussianRouletteClient.RussianRouletteService.User user) {
            return base.Channel.SignUpAsync(user);
        }
        
        public void SignIn(RussianRouletteClient.RussianRouletteService.User user) {
            base.Channel.SignIn(user);
        }
        
        public System.Threading.Tasks.Task SignInAsync(RussianRouletteClient.RussianRouletteService.User user) {
            return base.Channel.SignInAsync(user);
        }
        
        public void SendPublicMessage(RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message) {
            base.Channel.SendPublicMessage(user, message);
        }
        
        public System.Threading.Tasks.Task SendPublicMessageAsync(RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message) {
            return base.Channel.SendPublicMessageAsync(user, message);
        }
        
        public void SendPrivateMessage(RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message) {
            base.Channel.SendPrivateMessage(user, message);
        }
        
        public System.Threading.Tasks.Task SendPrivateMessageAsync(RussianRouletteClient.RussianRouletteService.User user, RussianRouletteClient.RussianRouletteService.UMessage message) {
            return base.Channel.SendPrivateMessageAsync(user, message);
        }
        
        public void InviteToPlay(string Nickname, RussianRouletteClient.RussianRouletteService.User user) {
            base.Channel.InviteToPlay(Nickname, user);
        }
        
        public System.Threading.Tasks.Task InviteToPlayAsync(string Nickname, RussianRouletteClient.RussianRouletteService.User user) {
            return base.Channel.InviteToPlayAsync(Nickname, user);
        }
        
        public void AgreeToPlay(string Nickname, RussianRouletteClient.RussianRouletteService.User user) {
            base.Channel.AgreeToPlay(Nickname, user);
        }
        
        public System.Threading.Tasks.Task AgreeToPlayAsync(string Nickname, RussianRouletteClient.RussianRouletteService.User user) {
            return base.Channel.AgreeToPlayAsync(Nickname, user);
        }
        
        public void Disconnect(RussianRouletteClient.RussianRouletteService.User user) {
            base.Channel.Disconnect(user);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(RussianRouletteClient.RussianRouletteService.User user) {
            return base.Channel.DisconnectAsync(user);
        }
        
        public bool checkSignIn(RussianRouletteClient.RussianRouletteService.User user) {
            return base.Channel.checkSignIn(user);
        }
        
        public System.Threading.Tasks.Task<bool> checkSignInAsync(RussianRouletteClient.RussianRouletteService.User user) {
            return base.Channel.checkSignInAsync(user);
        }
        
        public string[] GetUsersList() {
            return base.Channel.GetUsersList();
        }
        
        public System.Threading.Tasks.Task<string[]> GetUsersListAsync() {
            return base.Channel.GetUsersListAsync();
        }
        
        public string[] ReceiveTopPlayers() {
            return base.Channel.ReceiveTopPlayers();
        }
        
        public System.Threading.Tasks.Task<string[]> ReceiveTopPlayersAsync() {
            return base.Channel.ReceiveTopPlayersAsync();
        }
    }
}
