//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;
using System.ServiceModel;
using RussianRouletteServiceLibrary.Interfaces;

namespace RussianRouletteServiceLibrary.Data
{
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public User FirstPlayer { get; set; }
        public User SecondPlayer { get; set; }
        public User Winner { get; set; }

        public IGameCallback CurrentGameCallback
        {
            get
            {
                return OperationContext.Current.
                       GetCallbackChannel<IGameCallback>();
            }
        }

        public bool SearchUsersByNickname(string nickname)
        {
            return gameClientsDictionary.Keys.Any(c => c.NickName == nickname);
        }

        Dictionary<User, IGameCallback> gameClientsDictionary = new Dictionary<User, IGameCallback>();
    }
}
