//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;
using System.Runtime.Serialization;

namespace RussianRouletteServiceLibrary.Data
{
    using RussianRouletteServiceLibrary.Interfaces;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class Game
    {
        public int Id { get; set; }
        public int FirstPlayer { get; set; }
        public int SecondPlayer { get; set; }
        public Nullable<int> Winner { get; set; }
        public bool[] _cylinder { get; set; }

        public Dictionary<User, IGameCallback> clients;
        public List<User> playerList;

        public virtual User FirstUser { get; set; }
        public virtual User SecondUser { get; set; }
        public virtual User WinnerUser { get; set; }

        public Game(int id, User firstPlayer, User fecondPlayer)
        {
            clients = new Dictionary<User, IGameCallback>();
            playerList = new List<User>();
        }

        public bool SearchUsersByNickname(string nickname)
        {
            return clients.Keys.Any(c => c.NickName == nickname);
        }

    }
}
