//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianRouletteServiceLibrary.Data
{
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UMessages = new List<UMessage>();
            this.Games = new List<Game>();
        }
    
        public int Id { get; set; }
        public string NickName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<UMessage> UMessages { get; set; }
        public virtual ICollection<Game> Games { get; set; }
    }
}
